<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-EA4CD3Q6" failures="4" tests="10" name="Testfailed2" time="0.124" errors="0" timestamp="2021-11-18T14:03:56 IST">
  <testcase classname="failedTestCases.Failed_testcases_run" name="test21" time="0.012"/>
  <testcase classname="failedTestCases.Failed_testcases_run" name="test22" time="0.007">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.fail(Assert.java:95)
at failedTestCases.Failed_testcases_run.test22(Failed_testcases_run.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test22 -->
  <testcase classname="failedTestCases.Failed_testcases_run" name="test23" time="0.003">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.fail(Assert.java:95)
at failedTestCases.Failed_testcases_run.test23(Failed_testcases_run.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test23 -->
  <testcase classname="failedTestCases.Failed_testcases_run" name="test24" time="0.002"/>
  <testcase classname="failedTestCases.Failed_testcases_run" name="test25" time="0.002"/>
  <testcase classname="failed_test_cases2.Failed_test_cases_run2" name="Abc" time="0.004">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.fail(Assert.java:95)
at failed_test_cases2.Failed_test_cases_run2.Abc(Failed_test_cases_run2.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- Abc -->
  <testcase classname="failed_test_cases2.Failed_test_cases_run2" name="def" time="0.002"/>
  <testcase classname="failed_test_cases2.Failed_test_cases_run2" name="mno" time="0.002">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.fail(Assert.java:95)
at failed_test_cases2.Failed_test_cases_run2.mno(Failed_test_cases_run2.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- mno -->
  <testcase classname="failed_test_cases2.Failed_test_cases_run2" name="pqr" time="0.001"/>
  <testcase classname="failed_test_cases2.Failed_test_cases_run2" name="xyz" time="0.002"/>
</testsuite> <!-- Testfailed2 -->
